//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobMeEntities : DbContext
    {
        public JobMeEntities()
            : base("name=JobMeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchNumber> BatchNumbers { get; set; }
        public virtual DbSet<ServiceLookup> ServiceLookups { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<ServiceProvider_Accreditation> ServiceProvider_Accreditation { get; set; }
        public virtual DbSet<ServiceProvider_Image> ServiceProvider_Image { get; set; }
        public virtual DbSet<ServiceProvider_Location> ServiceProvider_Location { get; set; }
        public virtual DbSet<ServiceProvider_Recommendation> ServiceProvider_Recommendation { get; set; }
        public virtual DbSet<ServiceProvider_SubServiceType> ServiceProvider_SubServiceType { get; set; }
        public virtual DbSet<ServiceProvider_TermsAndConditions> ServiceProvider_TermsAndConditions { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<ServiceRequest_Invoice> ServiceRequest_Invoice { get; set; }
        public virtual DbSet<ServiceRequest_Invoice_Line> ServiceRequest_Invoice_Line { get; set; }
        public virtual DbSet<ServiceRequest_Invoice_Line_Item> ServiceRequest_Invoice_Line_Item { get; set; }
        public virtual DbSet<ServiceRequest_Quote> ServiceRequest_Quote { get; set; }
        public virtual DbSet<ServiceRequest_Quote_Line> ServiceRequest_Quote_Line { get; set; }
        public virtual DbSet<ServiceRequest_Quote_Line_Item> ServiceRequest_Quote_Line_Item { get; set; }
        public virtual DbSet<ServiceRequest_Rating> ServiceRequest_Rating { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<SouthAfricanCity> SouthAfricanCities { get; set; }
        public virtual DbSet<SubServiceType> SubServiceTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AvailableService> AvailableServices { get; set; }
    }
}
