//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest_Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest_Quote()
        {
            this.ServiceRequest_Invoice = new HashSet<ServiceRequest_Invoice>();
            this.ServiceRequest_Quote_Line = new HashSet<ServiceRequest_Quote_Line>();
        }
    
        public int Id { get; set; }
        public int ServiceRequestId { get; set; }
        public string QuoteNo { get; set; }
        public System.DateTime DateOfQuote { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public decimal Vat { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string PaymentGatewayRefNo { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest_Invoice> ServiceRequest_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest_Quote_Line> ServiceRequest_Quote_Line { get; set; }
    }
}
