//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SouthAfricanCity
    {
        public int CityId { get; set; }
        public string City { get; set; }
        public string AccentCity { get; set; }
        public string ProvinceName { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int ProvinceID { get; set; }
    }
}
